### ISSUE TITLE
Attempt to connect for initial configuration using macBook fails - fixed

### ISSUE THREAD

**Issue by DG12** [ruuvi/esp32-wifi-manager#25]
Selecting **Ruuvigateway mmmm** with
Catalina 10.15.6

captive network assistant fails and reports

A problem occured
The webpage couldn't be loaded

Looks like DNS reply is malformed (at least Mac OS thinks so)
```
/usr/bin/dig captive.apple.com 
;; Warning: Message parser reports malformed message packet.
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 110
;; flags: qr aa ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: Message has 16 extra bytes at end

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; Query time: 40 msec
;; SERVER: 10.10.0.1#53(10.10.0.1)
;; WHEN: Wed Aug 05 19:24:58 EDT 2020
;; MSG SIZE  rcvd: 62

```

```
I (4437199) wifi:new:<1,0>, old:<1,0>, ap:<1,0>, sta:<0,0>, prof:1
I (4437199) wifi:station: 4c:32:75:97:3b:ad join, AID=1, bgn, 20
(4437219) wifi_manager: WIFI_EVENT_AP_STACONNECTED
(4437389) dns_server: Replying to DNS request for captive.apple.com from 10.10.0.3
(4439559) tcpip_adapter: softAP assign IP to station,IP is: 10.10.0.3
(4440759) uart: advertisements in table:
(4441819) tcpip_adapter: softAP assign IP to station,IP is: 10.10.0.3
(4442099) ruuvidongle: free heap: 135892
(4444729) dns_server: Replying to DNS request for lb._dns-sd._udp.0.0.10.10.in-addr.arpa from 10.10.0.3
(4444729) dns_server: Replying to DNS request for db._dns-sd._udp.0.0.10.10.in-addr.arpa from 10.10.0.3
(4444739) dns_server: Replying to DNS request for b._dns-sd._udp.0.0.10.10.in-addr.arpa from 10.10.0.3
(4444829) dns_server: Replying to DNS request for www.apple.com from 10.10.0.3
(4444839) dns_server: Replying to DNS request for api.apple-cloudkit.com from 10.10.0.3
(4444839) dns_server: Replying to DNS request for 1-courier.sandbox.push.apple.com from 10.10.0.3
(4444849) dns_server: Replying to DNS request for 1-courier.push.apple.com from 10.10.0.3
```

```
(508) cpu_start: Project name: ruuvi_gateway_esp
(514) cpu_start: App version: v0.3.0-4-gfdbd64b
(519) cpu_start: Compile time: Jul 24 2020 12:49:55
```

This originally posted against gwui https://github.com/ruuvi/ruuvi.gwui.html/issues/29

**Comment by DG12** [comment]
Although dig complains, seems like handshake continues for several additional packets.

<img width="1276" alt="wifiStartupFails" src="https://user-images.githubusercontent.com/2365961/89476804-a5af1f00-d759-11ea-9e81-65887adb0d33.png">

Perhaps wireShark packet capture at [http://MyBeacons.info/ruuviGateway/wifiStartFail.pcapng.gz](http://MyBeacons.info/ruuviGateway/wifiStartFail.pcapng.gz) might help

**Comment by ojousima** [comment]
Thank you for the details. 
This might be a related issue: https://github.com/ruuvi/ruuvi.gateway_esp.c/issues/3.
Can you open the 10.10.0.1 at all? I can open the page with Catalina, but sometimes I need to try twice to load the page on my browser.

**Comment by DG12** [comment]
After many attempts I am able to get the configuration page with Safari (as well as curl)

**Comment by ojousima** [comment]
Here's what I get on a recent firmware:
```
/usr/bin/dig captive.apple.com 

; <<>> DiG 9.10.6 <<>> captive.apple.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```
Can you try with these binaries: https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/119/ ? 
Flashing instructions are at https://github.com/ruuvi/ruuvi.gateway_esp.c/blob/master/README.md#using-prebuilt-images

**Comment by DG12** [comment]
v0.3.0-4-gfdbd64b DOES work with OS X El Capitan !

**Comment by DG12** [comment]
Still no joy. 
Log at [http://mybeacons.info/ruuviGateway/200810.10:55.log](http://mybeacons.info/ruuviGateway/200810.10:55.log)
wifi capture(harder)?
I (520) App version:      v0.3.1-24-gc6467be
I (520) cpu_start: Compile time:     Aug  6 2020 13:02:08

**Comment by ojousima** [comment]
Thanks for the details @DG12 . 
@TheSomeMan please take a look when you have a chance.

**Comment by TheSomeMan** [comment]
Hi @DG12 
I checked the attached logs and didn't find any problems.

Wireshark logs:
frame 14: 10.10.0.2 -> 10.10.0.1: DNS query captive.apple.com
frame 15: 10.10.0.2 <- 10.10.0.1: DNS response captive.apple.com 10.10.0.1
frame 19: 10.10.0.2 -> 10.10.0.1: HTTP GET /hotspot-detect.html
frame 22: 10.10.0.2 <- 10.10.0.1: HTTP/1.1 302 Found Location: http://10.10.0.1
frame 29: 10.10.0.2 -> 10.10.0.1: HTTP GET /
frame 30: 10.10.0.2 <- 10.10.0.1: HTTP/1.1 200 OK Content-type: text/html Content-Length: 5659 Content-Encoding: gzip

body: [index.html.gz](https://github.com/ruuvi/esp32-wifi-manager/files/5609079/index.html.gz)

So, Safari got correct answer from the gateway and it should work as expected.

I also checked DNS request/response - there are no extra bytes at the end of response, so this message "WARNING: Message has 16 extra bytes at end" might be incorrect or it was caused by some problem on your Mac.

> v0.3.0-4-gfdbd64b DOES work with OS X El Capitan !

I also checked on "OS X 10.10 Yosemite" and it works good, but unfortunately my Mac is quite old and I can't test if this problem manifests itself on the latest versions "macOS 10.15 Catalina" or "macOS 11 Big Sur".

If you have a chance, please test the latest developer build: [https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/197/](https://jenkins.ruuvi.com/job/ruuvi_gateway_esp-PR/197/)
Flashing instructions are at https://github.com/ruuvi/ruuvi.gateway_esp.c/blob/master/README.md#using-prebuilt-images

**Comment by DG12** [comment]
@TheSomeMan as of V1.2.2-24-g888f759 Niv 27 2020 17:10:57
Safari on BigSur connect to 192.168.1.56 delay 30 seconds then 6 alerts popup:
get_config:unhandled key: use_coded_phy, ...use_1mbit_phy, ...use_extended_payload,
...use_channel_37,  ...38, ...39

since this is not first time, #welcome blinks, then wifi config is loaded from save configuration and #wifi-connected is shown.
